### ISSUE TITLE
Upgrade from 0.5.3 to 0.5.4 fails -- missing core.clj

### ISSUE THREAD

**Issue by hlship** [weavejester/medley#11]
Looking at the Maven artifact, there's just the core.cljx file, no core.clj file.  Did something significant change in this release related to that?

**Comment by weavejester** [comment]
Drat. I did update the dependencies. The combination of cljx and clojurescript always seem to break something. Let me fix it and re-release.

**Comment by weavejester** [comment]
Okay, should be fixed in 0.5.5.
