### ISSUE TITLE
Transducer versions for functions over collections

### ISSUE THREAD

**Issue by hyPiRion** [weavejester/medley#12]
Would it be interesting to provide transducer variants for the medley functions that runs over collections? `distinct-by`, `take-upto`, `drop-upto`, `indexed` and probably some others do have transducer variants which could be useful.

**Comment by weavejester** [comment]
Yep, that would be a good idea.

**Comment by madstap** [comment]
Would it make sense for the functions that work on maps, like `map-keys` and `filter-vals`, to have transducer versions?

**Comment by weavejester** [comment]
I don't *think* so, because transducers tend to work with some kind of ordered stream of data, and maps don't really fit into that category well. However, I might be wrong.

**Comment by weavejester** [comment]
Transducer versions have been written for the named functions.

**Comment by yuhan0** [comment]
I think it would be useful to have transducer versions of the functions acting on maps, especially for multiple chained transformations on a single collection.

Essentially you could use `(into {} xform coll)` and the reducing functions would act on a sequence of map-entry pairs - this would avoid having to call `reduce-map` multiple times and create intermediate collections.

Here's an example, from a quick benchmark the transducer version performs 2x as fast:
```clojure
;; Transducer
(into {}
  (comp
    (map name)
    (index-by first)
    (map-keys int)
    (remove-vals #(even? (count %))))
  [:abc :defg :hijkl :mnopq :rstu :vwx :yz])
;; => {97 "abc", 104 "hijkl", 109 "mnopq", 118 "vwx"}

;; Equivalent threading macro (creates intermediate colls)
(->> [:abc :defg :hijkl :mnopq :rstu :vwx :yz]
  (map name)
  (index-by first)
  (map-keys int)
  (remove-vals #(even? (count %))))
;; => {97 "abc", 104 "hijkl", 109 "mnopq", 118 "vwx"}
```

If this looks like a useful addition, I'll go ahead and open a PR :)

**Comment by weavejester** [comment]
Yes, I think that seems useful.
