### ISSUE TITLE
map-vals loses meta-data of containing collection [0.7.1]

### ISSUE THREAD

**Issue by hlship** [weavejester/medley#13]
I've found that if I have a collection, a map with meta data, and execute medley/map-vals upon it, the resulting map does not have the meta-data.

```
(require '[medley.core :as medley])
=> nil
(def x (with-meta {:my-meta 1} {:foo 1}))
=> #'user/x
(-> (medley/map-vals inc x) meta)
=> nil
(meta x)
=> {:foo 1}
```

**Comment by weavejester** [comment]
That's how `clojure.core/mapv` works:

```clojure
user=> (def x (with-meta [1] {:foo 1}))
#'user/x
user=> (meta (mapv inc x))
nil
user=> (meta x)
{:foo 1}
```

**Comment by hlship** [comment]
I'd love a clarification on what functions maintain metadata. I've asked on Slack but no response so far. May need to add an issue.

**Comment by weavejester** [comment]
Collection functions don't seem to maintain metadata. So `map`, `filter`, `remove` etc. This is why the equivalent functions in Medley act in the same way.

**Comment by hlship** [comment]
I've added a `copying-meta` macro to my toolchest project for this purpose.
