### ISSUE TITLE
Additional map-transformation functions

### ISSUE THREAD

**Issue by dm3** [weavejester/medley#16]
Would you consider adding the following:

- [ ] `map-vals-with-keys :: (K -> V -> V') -> Map[K, V] -> Map[K, V']` (or `map-kv-vals`)
- [ ] `map-keys-with-vals :: (K -> V -> K') -> Map[K, V] -> Map[K', V]` (or `map-kv-keys`)

?

I seem to run into the former all the time and doing `map-kv` always seems unnecessary.

**Comment by weavejester** [comment]
I'll consider it, but my initial thought it that this *might* be a little too specific.
