### ISSUE TITLE
Interactive docs

### ISSUE THREAD

**Issue by viebel** [weavejester/medley#19]
Hi James,

`medley` is self-host cljs compatible. It runs fine on [klipse](http://app.klipse.tech/?cljs_in=(require%20%27%5Bmedley.core%20%3Aas%20m%20%3Arefer%20%5Bmap-vals%5D%5D)%0A%0A%0A(map-vals%20inc%20%7B%3Aa%201%20%3Ab%202%7D)&external-libs=%5Bhttps%3A%2F%2Fraw.githubusercontent.com%2Fweavejester%2Fmedley%2Fmaster%2Fsrc%2F%5D).

Would you like to have an interactive version of the documentation with the klipse codox theme?

**Comment by weavejester** [comment]
Last time I looked at Klipse docs there was a few seconds of delay loading them. I think I'd rather keep the documentation snappy in Medley's case, as it's one of those libraries where the API docs are going to be quickly checked for a single function.
