### ISSUE TITLE
Deep-merge?

### ISSUE THREAD

**Issue by vemv** [weavejester/medley#30]
Hi James,

what would be your thoughts on adding deep-merge? Seems a pretty common need.

https://github.com/r0man/noencore/blob/24ac307f132ec3e72f8dd133fc417ec734458a1e/src/no/en/core.cljc#L274 looks fine - simply I'd rather consume just one "utils" library than _n_.

**Comment by weavejester** [comment]
I think I'd be fine with that. I've had to implement a `deep-merge` myself at some point. However, I'd like to ensure that the function is as efficient as we can make it - I think we can improve on the implementation you linked.

**Comment by vemv** [comment]
Nice one, thank you!
