### ISSUE TITLE
add a new function `dates` ?

### ISSUE THREAD

**Issue by yellowbean** [weavejester/medley#34]
Hello, Mr Reeves.

Great repository here ! since in Clojure.core we have  function `doubles` to initiate a double array from a collection. Do you think whether it is a good idea to include a `dates` in  `medley` ?

basically it can be written as 

    (defn dates [ x ]
        (into-array LocalDate x ))

**Comment by weavejester** [comment]
I think this is a little too narrow a use-case for Medley.
