### ISSUE TITLE
Variadic version of map-vals

### ISSUE THREAD

**Issue by yuhan0** [weavejester/medley#35]
Would it be a good idea for `map-vals` to accept multiple collections with a variadic function, just like regular `map` and `mapcat`?

```clojure
(map-vals min
  {:x 1 :y 4 :z 20}
  {:x 3 :y -6 :z 15}
  {:x 0 :y 8 :z 16})
;; => {:x 0, :y -6, :z 15}

(map-vals concat
  {:xs [1 2 3] :ys [4 5 6]}
  {:xs [3 2 1] :ys [7 8 9]})
;; => {:xs (1 2 3 3 2 1), :ys (4 5 6 7 8 9)}
```

It would break symmetry with `map-keys` and `map-kv`, which don't seem to have an intuitive analogue for being applied to multiple colls.

Also I'm not sure how missing or extra keys should be handled:
```clojure
(map-vals + {:foo 10} {:foo 5 :bar 6})
;; => {:foo 15 :bar ??}
```

**Comment by weavejester** [comment]
It's not a bad idea. I assume it work work the same way as `map` for missing keys, so it would ignore keys that aren't common throughout.

```clojure
(map + [10] [5 6])
;; => (15)

(map-vals + {:foo 10} {:foo 5 :bar 6})
;; => {:foo 15}
```
