### ISSUE TITLE
select-some

### ISSUE THREAD

**Issue by borkdude** [weavejester/medley#37]
Would you be interested in a PR for this?

``` clojure
(defn select-some
  "Like select-keys, but only selects when value is not nil."
  ([m ks]
   (persistent!
    (reduce (fn [acc k]
              (if-some [v (get m k)]
                (assoc! acc k v)
                acc))
            (transient {})
            ks))))

;; example:
(select-some {:a 1 :b nil :c 2 :d false} [:a :b :d]) ;; => {:a 1, :d false}
```

**Comment by eraserhd** [comment]
This library now has `update-existing`, so perhaps `select-existing` would be the better name?

**Comment by borkdude** [comment]
@eraserhd Hi Jason. existing might not be right right name for something which doesn't select keys that do exist, but are nil?

**Comment by eraserhd** [comment]
@borkdude Oh, I did fail to read closely.  Carry on...

**Comment by weavejester** [comment]
I think the use-case for this might be a little narrow, but I'll take some time to consider this.

**Comment by borkdude** [comment]
@weavejester That makes sense. I "needed" this function here:

https://github.com/borkdude/clj-kondo/blob/34ee8736045e14e0b2e5109010793f48c1def132/src/clj_kondo/impl/analysis.clj#L13

where I wanted to merge with another map, where the other map is produced by select-keys, but I only want the extra keys if they are non-nil.

Maybe there's another good way to do it without using an elaborate `(cond-> ...)` .

**Comment by weavejester** [comment]
You could always write: `(remove-vals nil? (select-keys m ks))`
