### ISSUE TITLE
Does find-first belong?

### ISSUE THREAD

**Issue by ToBeReplaced** [weavejester/medley#5]
I'm wondering if `find-first` belongs in this library.

I would argue against its inclusion because it is simple enough for anyone to write and is not any more clear than explicitly typing `(first (filter pred coll))`.  Moreover, the simpler, composable method allows for `find-last` or `remove-first` and the like.

Contrast this with the difficulty of writing a performant version of `map-keys`.

**Comment by astoeckley** [comment]
Just curious the rationale for this over `some`:

https://clojuredocs.org/clojure.core/some
