### ISSUE TITLE
Suggested addition: ClojureCLR support

### ISSUE THREAD

**Issue by E-A-Griffin** [weavejester/medley#64]
I think adding ClojureCLR support would be beneficial, especially in the greater effort to port Clojure(Script) libraries to ClojureCLR which doesn't seem to have nearly as fully developed support in terms of community libraries. I understand that adding support for ClojureCLR would be an ongoing commitment rather than a quick fix, but I would be willing to contribute time and effort where I can to maintaining these additions.

**Comment by weavejester** [comment]
I'm fine with this in theory, as long as testing is automated and part of CI.

**Comment by E-A-Griffin** [comment]
Any updates on the open pull request?
