### ISSUE TITLE
medley/join may occur StackOverflowError in rare cases

### ISSUE THREAD

**Issue by velios** [weavejester/medley#66]
```
(reduce (fn [acc coll]
          (medley/join [acc coll]))
        []
        (map (fn [v]
               [v v])
             (range 10000)))
```

Execution leads to StackOverflowError due using concat

Same described https://stuartsierra.com/2015/04/26/clojure-donts-concat

Rare case, but may happen

More examples here https://gist.github.com/stuartsierra/9982776

**Comment by weavejester** [comment]
Sure, but this seems unavoidable for the same reasons its unavoidable in `concat`? Or do you have a solution?

**Comment by velios** [comment]
(reduce (fn [acc coll]
          (into acc coll))
        []
        (map (fn [v]
               [v v])
             (range 10000)))
             
This solution avoids the described problems on my project, but it needs to be improved, if at all suitable in the case of medley/join

**Comment by weavejester** [comment]
That solution works because `into` is not lazy.
