### ISSUE TITLE
Suggested addition: mapmap

### ISSUE THREAD

**Issue by port19x** [weavejester/medley#71]
(your issue template might be broken btw)

like map, but one level deeper.
Given a sequence (lvl1) of sequences (lvl2), map function to those sequences (lvl2) of the sequence.
Especially useful because you can't nest short form lambdas `#(fn %)`

**Comment by weavejester** [comment]
I think this is a little too specific for Medley. (I also don't have an issue template set on this project.)

**Comment by port19x** [comment]
fair enough, thx for the quick response
