### ISSUE TITLE
`time` as data?

### ISSUE THREAD

**Issue by vemv** [weavejester/medley#77]
Hey James,

one fairly usual need I have in Clojure projects is to `time` things, and obtain the timing result as data.

Wrapping `clojure.core/time` in a `with-out-str` can have unintended effects and needs parsing anyway.

So a `time` in medley that returned `[computation, timing]` might not look out of place.

Cheers - V

**Comment by weavejester** [comment]
I think this would be better suited to a more specific profiling library. There's a lot of subtleties in correctly profiling code that I don't think fit in a more general-purpose library like Medley.
