### ISSUE TITLE
Add conj-some fn

### ISSUE THREAD

**Issue by velios** [weavejester/medley#81]
Good afternoon. Thanks for your great set of tools. I wanted to know what you think about adding a conj-some feature similar to a [conj-when](https://github.com/plumatic/plumbing/blob/424bc704f2db422de34269c139a5494314b3a43b/src/plumbing/core.cljc#L255C7-L255C16) in plumbing, but only if it's not nil, not for all falsey values . It seems enough general-purpose for me.
With this can do thigs like this and this looks to me to continue the logic of your library
```clojure
(reduce conj-some [] [:a (when (true? false-x) :b)]
=> [:a] ;;; not [:a nil] with regular conj
```

**Comment by weavejester** [comment]
I'm unsure if this adds enough benefit over filtering via a transducer:

```clojure
(reduce conj-some [] coll)
(into [] (filter some?) coll)
```

The two expressions are almost the same length. Is there any other situation where this would save more than 3 characters?

**Comment by velios** [comment]
No, I don’t think I have more clear examples. I just didn't have the imagination to do it on transducers.
