### ISSUE TITLE
insert-nth: ability to use negative numbers

### ISSUE THREAD

**Issue by velios** [weavejester/medley#88]
Hi. First of all thx for great tooling.

```clojure
(require '[medley.core :as medley])
;; Proposal
(let [coll [1 2 3 4 5]]
         (medley/insert-nth -1 :a coll))
;; Suggests the same result as
(let [coll [1 2 3 4 5]
             coll-len (count coll)]
         (medley/insert-nth (dec coll-len) :a coll))
;; => (1 2 3 4 :a 5)
```

**Comment by weavejester** [comment]
I think this might be a little too specific for Medley.

**Comment by tomdl89** [comment]
Also this implementation would kill laziness in lazy sequences by trying to count them.

**Comment by velios** [comment]
That's right, I forgot that the lazy sequence returns there... We'll have to do it the old fashioned way. butlast, last, concat is our friends
