### ISSUE TITLE
Suggested addition: removev and keepv

### ISSUE THREAD

**Issue by velios** [weavejester/medley#94]
Hello. First of all, thank you very much for the great library. 

Follow the description `useful, mostly pure functions that are "missing" from clojure.core`. Among the functions that I feel so is `removev` and `keepv`.
At some point I came across [Clojure's deadly sin
 article](https://clojure-goes-fast.com/blog/clojures-deadly-sin/) about lazy calculations. And since then I prefer to write flows in most cases in eager manner like this, instead of using "default" lazy with `map` approach:

```clojure
(->> (repeat 1000 10)
      (mapv inc)
      (mapv inc)
      (mapv #(* % 2))
      (mapv inc)
      (mapv inc))
```

We also have a function in the standard library that continues this logic. `filterv`
But for some reason unknown to me, there are no functions `removev` and `keepv`, which, together with `mapv` and `filter`, are often used in thread last macro(->>)

Also, in my practice, I work mostly with small data sequenes, not infinite.
Besides being faster it is also more logical when using debuggers such as Flowstorm's stepper.

True, we can use transducers instead and it will even be faster. But this approach is more unusual, especially when you work in a team.

```clojure
(into []
       (comp (map inc)
             (map inc)
             (map #(* % 2))
             (map inc)
             (map inc))
       (repeat 1000 10))
```

Example of possible usage:

```clojure
(->> [1 2 3 4 5 6 11 12 13 14]
      (mapv inc)
      (filterv odd?)
      (medley/removev #(> % 10))
      (medley/keepv #(when (odd? %) %)))
;; => [3 5 7]
```

Let me know if this is an acceptable proposal, but you do not have time to implement it and I will try to prepare a PR.

**Comment by velios** [comment]
Do you think I should do PR or is this a completely inappropriate idea?

**Comment by weavejester** [comment]
Apologies for the delayed response. I thought I had actually replied to this!

I think that in this case I'd rather not have `keepv` and `filterv` as it feels like a slippery slope of having to have a vector function for every seq function.

**Comment by velios** [comment]
Yes, I understand what you mean. To be consistent you just have to start and not stop. dropv, restv, etc =D The base 4 felt a little more native in my head, but I think ultimately you're right.
